<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Executive Summary - {{ $fy }}</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #0f172a; }
        h1, h2, h3 { margin: 0 0 8px 0; }
        .muted { color: #64748b; }
        .section { margin-top: 18px; }
        .grid { width: 100%; border-collapse: collapse; }
        .grid th, .grid td { border: 1px solid #e2e8f0; padding: 8px 10px; vertical-align: top; }
        .grid th { background: #f8fafc; text-align: left; }
        .kpis { width: 100%; border-collapse: collapse; }
        .kpis td { border: 1px solid #e2e8f0; padding: 10px; }
        .small { font-size: 10px; }
    </style>
</head>
<body>
    <h1>Executive Summary</h1>
    <div class="muted">Fiscal year: {{ $range['label'] }} | Generated by user: {{ $generatedBy ?? 'N/A' }}</div>

    <div class="section">
        <table class="kpis">
            <tr>
                <td><strong>Total funding</strong><br>₹{{ number_format($summary['total_funding_cr'], 1) }} Cr</td>
                <td><strong>YoY growth</strong><br>{{ ($summary['yoy_growth'] >= 0 ? '+' : '') . $summary['yoy_growth'] }}%</td>
                <td><strong>Approved grants</strong><br>{{ number_format($summary['approved_grants']) }}</td>
                <td><strong>Printable reports</strong><br>{{ number_format($summary['printable_reports']) }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <h2>Year-over-year comparison</h2>
        <table class="grid">
            <thead>
                <tr>
                    <th>Metric</th>
                    <th>{{ $yoy['fy1_label'] }}</th>
                    <th>{{ $yoy['fy2_label'] }}</th>
                    <th>Change</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($yoy['comparison'] as $row)
                    <tr>
                        <td>{{ $row['metric'] }}</td>
                        <td>{{ $row['fy1_value'] }}</td>
                        <td>{{ $row['fy2_value'] }}</td>
                        <td>{{ ($row['change'] >= 0 ? '+' : '') . $row['change'] }}%</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Monthly detail</h2>
        <table class="grid">
            <thead>
                <tr>
                    <th>Month</th>
                    <th>Funding (USD)</th>
                    <th>Cumulative (Cr)</th>
                    <th>Registrations</th>
                    <th>Recognized</th>
                    <th>Approval %</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($monthly as $row)
                    <tr>
                        <td>{{ $row['month_label'] }}</td>
                        <td>
                            @php
                                $fundingUsd = (float) $row['funding_usd'];
                                echo match (true) {
                                    $fundingUsd >= 1e9 => '$' . number_format($fundingUsd / 1e9, 2) . 'B',
                                    $fundingUsd >= 1e6 => '$' . number_format($fundingUsd / 1e6, 1) . 'M',
                                    $fundingUsd >= 1e3 => '$' . number_format($fundingUsd / 1e3, 0) . 'K',
                                    $fundingUsd > 0 => '$' . number_format($fundingUsd, 2),
                                    default => '—',
                                };
                            @endphp
                        </td>
                        <td>₹{{ number_format((float) $row['cumulative_usd'], 1) }} Cr</td>
                        <td>{{ number_format((int) $row['registrations']) }}</td>
                        <td>{{ number_format((int) $row['recognized']) }}</td>
                        <td>{{ number_format((float) $row['approval_pct'], 1) }}%</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</body>
</html>
