<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>State Analytics - {{ $fy }}</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #0f172a; }
        h1, h2 { margin: 0 0 8px 0; }
        .muted { color: #64748b; }
        .section { margin-top: 18px; }
        .grid { width: 100%; border-collapse: collapse; }
        .grid th, .grid td { border: 1px solid #e2e8f0; padding: 8px 10px; vertical-align: top; }
        .grid th { background: #f8fafc; text-align: left; }
        .kpis { width: 100%; border-collapse: collapse; }
        .kpis td { border: 1px solid #e2e8f0; padding: 10px; }
    </style>
</head>
<body>
    <h1>State Analytics Pack</h1>
    <div class="muted">Fiscal year: {{ $range['label'] }} | Generated by user: {{ $generatedBy ?? 'N/A' }}</div>

    <div class="section">
        <h2>State ranking snapshot</h2>
        <table class="grid">
            <thead>
                <tr>
                    <th>State</th>
                    <th>Code</th>
                    <th>Tier</th>
                    <th>Active startups</th>
                    <th>Funding (Cr)</th>
                    <th>Dominant sector</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($states as $state)
                    <tr>
                        <td>{{ $state->state_name }}</td>
                        <td>{{ $state->state_code }}</td>
                        <td>{{ $state->tier }}</td>
                        <td>{{ number_format($state->active_startups) }}</td>
                        <td>₹{{ number_format($state->funding_inr_cr, 1) }} Cr</td>
                        <td>{{ $state->dominant_sector }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</body>
</html>
